name: E2E Testing
on:
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    name: E2E Testing on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    env:
      DOWNLOAD_TIMEOUT: 220000
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install node-canvas deps (macos)
        if: matrix.os != 'ubuntu-latest'
        run: brew install pkg-config cairo pango libpng jpeg giflib librsvg pixman
      - name: Install dependencies
        run: npm ci
        env:
          DETECT_CHROMEDRIVER_VERSION: true
      - name: Install xvfb (linux)
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install xvfb
      - name: Run E2E on chrome (linux)
        if: matrix.os == 'ubuntu-latest'
        run: xvfb-run --server-args="-screen 0, 1400x1000x24" --auto-servernum npm run test:e2e:chrome
      - name: Set screen resolution (windows)
        if: matrix.os == 'windows-latest'
        run: Set-DisplayResolution -Width 1920 -Height 1080 -Force
        shell: pwsh
      - name: Run E2E on chrome (non-linux)
        if: matrix.os != 'ubuntu-latest'
        run: npm run test:e2e:chrome
      - name: Archive test results
        if: success() || failure()
        uses: actions/upload-artifact@v4
        continue-on-error: true
        with:
          name: image_comparison_results_${{ matrix.os }}
          path: .tmp
          retention-days: 5
